"""Trip posts and comment

Revision ID: 0267e4948f09
Revises: b2f70c7600eb
Create Date: 2018-12-11 21:33:57.239948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0267e4948f09'
down_revision = 'b2f70c7600eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'trip', ['trip_id'], ['id'])
    op.add_column('trip', sa.Column('comment', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'comment')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'trip_id')
    # ### end Alembic commands ###
