"""trip_id

Revision ID: 27a931366206
Revises: 1ba417fa604e
Create Date: 2018-12-26 16:36:21.636480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a931366206'
down_revision = '1ba417fa604e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('trip_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'trip_id')
    # ### end Alembic commands ###
