"""notifications2

Revision ID: 94467f2845c5
Revises: 900d8b0c88a4
Create Date: 2018-12-16 21:19:09.208810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94467f2845c5'
down_revision = '900d8b0c88a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('body', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'body')
    # ### end Alembic commands ###
