"""subscribe u

Revision ID: c8fd468f09f8
Revises: 730c906b8a84
Create Date: 2019-01-23 19:44:53.706846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fd468f09f8'
down_revision = '730c906b8a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscribe', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribe', type_='foreignkey')
    op.drop_column('subscribe', 'user_id')
    # ### end Alembic commands ###
