"""notices

Revision ID: f0d00f4a2444
Revises: 27a931366206
Create Date: 2019-01-19 17:41:03.008261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d00f4a2444'
down_revision = '27a931366206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_name'), 'notice', ['name'], unique=False)
    op.create_index(op.f('ix_notice_timestamp'), 'notice', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notice_timestamp'), table_name='notice')
    op.drop_index(op.f('ix_notice_name'), table_name='notice')
    op.drop_table('notice')
    # ### end Alembic commands ###
